name: aplikasikoperasiundiksha
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.19.0
  permission_handler: ^11.0.0
  qr_code_scanner: ^1.0.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/undiksha.png
    - assets/pto.jpg
